pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'Amazon/Amazon-Web/target/*.war', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                dir('Amazon') {
                    sh 'ansible-playbook -i ansible/inventory.ini ansible/site.yml'
                }
            }
        }

        stage('Health Check') {
            steps {
                dir('Amazon') {
                    sh './scripts/health_check.sh 20.219.152.32'
                }
            }
        }

    }
}
