pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('Amazon') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'Amazon/Amazon-Web/target/*.war', fingerprint: true
            }
        }
    }
}
