---
- name: Deploy Amazon Application
  hosts: web
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Java 21 is installed
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Tomcat 10
      apt:
        name: tomcat10
        state: present

    - name: Enable Tomcat
      service:
        name: tomcat10
        enabled: yes
        state: started

    - name: Copy WAR file
      copy:
        src: ../Amazon-Web/target/Amazon.war
        dest: /var/lib/tomcat10/webapps/Amazon.war
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat10
        state: restarted
